name: PHP - Code quality

on:
  pull_request:

env:
  PHP_VERSION: 8.3.0

jobs:
  cache_dependencies:
    name: Fetch composer dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest changes
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Prepare/restore dependencies cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          # NOTE: the allows to reuse it if the composer.json has not changed
          key: composer/${{ runner.os }}/${{ hashFiles('**/composer.json') }}
          path: |
            composer.lock
            vendor/
      - name: Install/update dependencies
        uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3
        with:
          php_version: ${{ env.PHP_VERSION }}
          args: --ignore-platform-reqs

  php_analysis:
    name: Code quality checks
    runs-on: ubuntu-latest
    needs: [cache_dependencies]
    strategy:
      fail-fast: false
      matrix:
        tool: [phpcs, phpmd, phpstan, phpunit]
    steps:
      - name: Setup PHP ${{ env.PHP_VERSION }} environment
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Fetch lastest changes
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Restore dependencies cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          key: composer/${{ runner.os }}/${{ hashFiles('**/composer.json') }}
          path: |
            composer.lock
            vendor/
      - name: Run ${{ matrix.tool }}
        run: make ${{ matrix.tool }}-ci
      - name: Upload ${{ matrix.tool }} reports
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        if: always()
        with:
          name: ${{ matrix.tool }}-reports
          path: build/**/*.junit.xml
          retention-days: 1

  php_report:
    name: Report PHP code quality
    runs-on: ubuntu-latest
    needs: [php_analysis]
    if: always()
    steps:
      - name: Create build/ directory
        run: mkdir -p build

      # NOTE: only phpunit, phpcs generate reports
      - name: Download phpunit reports
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: phpunit-reports
          path: build/
      - name: Download phpcs reports
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: phpcs-reports
          path: build/

      - name: Report analisys results
        uses: mikepenz/action-junit-report@5b7ee5a21e8674b695313d769f3cbdfd5d4d53a4
        with:
          check_name: See PHP code quality reports
          report_paths: build/reports/*.xml
