name: PHP - Code quality

on:
  pull_request:

env:
  PHP_VERSION: 8.3.0

jobs:
  cache_dependencies:
    name: Fetch composer dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest changes
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Prepare/restore dependencies cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          # NOTE: the allows to reuse it if the composer.json has not changed
          key: composer/${{ runner.os }}/${{ hashFiles('**/composer.json') }}
          path: |
            composer.lock
            vendor/
      - name: Install/update dependencies
        uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3
        with:
          php_version: ${{ env.PHP_VERSION }}
          args: --ignore-platform-reqs

  php_analysis:
    name: Code quality checks
    runs-on: ubuntu-latest
    needs: [cache_dependencies]
    strategy:
      fail-fast: false
      matrix:
        tool: [phpcs, phpmd, phpstan, phpunit]
    steps:
      - name: Setup PHP ${{ env.PHP_VERSION }} environment
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Fetch lastest changes
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Restore dependencies cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          key: composer/${{ runner.os }}/${{ hashFiles('**/composer.json') }}
          path: |
            composer.lock
            vendor/
      - name: Run ${{ matrix.tool }}
        run: make ${{ matrix.tool }}-ci
      - name: Upload ${{ matrix.tool }} reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        if: always()
        with:
          name: ${{ matrix.tool }}-reports
          path: build/**/*.junit.xml
          retention-days: 1

  php_report:
    name: Report PHP code quality
    runs-on: ubuntu-latest
    needs: [php_analysis]
    if: always()
    steps:
      - name: Create build/ directory
        run: mkdir -p build

      # NOTE: only phpunit, phpcs generate reports
      - name: Download phpunit reports
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: phpunit-reports
          path: build/
      - name: Download phpcs reports
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: phpcs-reports
          path: build/

      - name: Report analisys results
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe
        with:
          check_name: See PHP code quality reports
          report_paths: build/reports/*.xml
